### ISSUE TITLE
Unauthenticated upvote results in 500 error

### ISSUE THREAD

**Issue by jelleroorda** [ploi/roadmap#191]
Clicking the upvote button when you’re not logged in results in a server error. I’d expect you to be redirected to the login page instead.

![5EE2EDBA-3A12-470E-9657-4CA3DA3756DC](https://user-images.githubusercontent.com/9193686/204530596-8d20a4c1-6b96-46d3-bbc1-e8ace76097f4.jpeg)

**Comment by st3f** [comment]
This Issue can be closed, you already fixed that

**Comment by Cannonb4ll** [comment]
Ah, yes, forgot. Thanks!
