### ISSUE TITLE
Is there a way to see everything others have submitted?

### ISSUE THREAD

**Issue by lao9s** [ploi/roadmap#214]
I disabled this option: "_Users can select a project when creating an item_", because I want to analyze the feature request then I'll put it on the right project.

On the page Settings->Dashboard items I see only: 
- recent items
- recent comments

I like how [Fider](https://fider.io/) shows on the home page all the feature requests, but they don't have roadmap boards.

What solutions could be fit for me?

**Comment by Cannonb4ll** [comment]
We currently have 2 options (widgets) for that, but it's flexible and could have more. Feel free to submit a PR with new widgets and the option inside that setting!

**Comment by lao9s** [comment]
Thank you. I'll do that.
