### ISSUE TITLE
How to hide content if not logged ?

### ISSUE THREAD

**Issue by dgillier** [ploi/roadmap#226]
hello,

Is there a way to hide content if user is not logged ?
(.env variable ?)

Thanks,
Denis

**Comment by Cannonb4ll** [comment]
You can mark an item as "Private" inside the "Management" tab of an item.

**Comment by dgillier** [comment]
I was looking for a global solution (all content) ,as it's for an employee only system.
Also related is there a way to only allow SSO login (for the same reason) ?

**Comment by erigglem** [comment]
> I was looking for a global solution (all content) ,as it's for an employee only system. Also related is there a way to only allow SSO login (for the same reason) ?

Did you ever figure this out? I'm in the same boat, I'd like to host this publicy but have every element of it hidden from public view behind a login.

Wondering what it would take to accomplish...

**Comment by dgillier** [comment]
I manage to allow SSO only.
Changed a few blade files to remove registrations UI and changed the web.php line 13 from :
Auth::routes();
to
Auth::routes(['register' => false]);
 
But did not go further…
