### ISSUE TITLE
Call to undefined method App\Models\User::canAccessFilament()

### ISSUE THREAD

**Issue by abdelhamiderrahmouni** [ploi/roadmap#245]
![Screenshot from 2023-11-01 13-01-59](https://github.com/ploi/roadmap/assets/26693672/7f2366be-6eec-4603-a854-559610c3c18c)
 
Steps to reproduce
1 create a projet in admin panel
then access it from to root url (ex: localhost:8000//projects/NAME_OF_PROJECT)
then click on Board name (ex: Planned)

**Comment by Cannonb4ll** [comment]
I wasn't able to replicate, because you left one part out, you need to check "Private". Saw the bug, will fix.
