### ISSUE TITLE
There are texts that are not being translated.

### ISSUE THREAD

**Issue by adaniieel** [ploi/roadmap#254]
There are texts that cannot be translated. I took on the task of translating all the current texts starting from /lang/en, copied and translated everything, but there are still several texts that have not been translated.

**Public view:**
![image](https://github.com/ploi/roadmap/assets/23020662/734ad152-e6c4-4fb2-8e4b-3b6099460a79)
![image](https://github.com/ploi/roadmap/assets/23020662/1d3bd42f-e1c6-473b-bf87-1b2fd106f27a)
![image](https://github.com/ploi/roadmap/assets/23020662/24f2ae69-b997-429d-a508-53284785101e)
![image](https://github.com/ploi/roadmap/assets/23020662/17f931bd-50d4-4bd3-b192-0383b718165a)
![image](https://github.com/ploi/roadmap/assets/23020662/23aefd93-2596-44c7-aa33-f1f4d6e133bd)

**Private view:**
![image](https://github.com/ploi/roadmap/assets/23020662/36fbb2cb-46c5-4d43-8e5b-67d34d46f7a4)
![image](https://github.com/ploi/roadmap/assets/23020662/0443559d-6256-42e6-89f6-46d70694c1f6)
![image](https://github.com/ploi/roadmap/assets/23020662/49c7aba0-fe5f-43f1-b95c-5b66bf6bf60e)

**_It's missing many more. Do you need me to identify them?_**

I would like to help more with this. I tried, but I don't have in-depth knowledge of Laravel. If you provide the missing texts in /lang/en, I could translate them to /lang/es.

**Comment by Autive** [comment]
I am busy with a new PR to make almost everything translatable but it will take some time. 
But expect a lot of new strings you can translate to es soon. Ill cover nl.

**Comment by Autive** [comment]
#259 created to make more translations possible. When merged you can add the ES translation @adaniieel.

**Comment by Autive** [comment]
@Cannonb4ll was not able to find the Changelog breadcrumb item where it is defined.

**Comment by adaniieel** [comment]
> #259 created to make more translations possible. When merged you can add the ES translation @adaniieel.

Nice! When your PR is ready, I will translate it into Spanish.

**Comment by Autive** [comment]
@adaniieel its merged into main, so go ahead :).

**Comment by adaniieel** [comment]
Hello @Autive nice job!!

I have had the opportunity to review all the work and it is very good.

There are some texts that are missing, and I know that I should fix it myself, but at the moment I don't have the knowledge, so I will just leave the report of the last thing that is missing so that the application is fully translated, if you could run it I would appreciate it.

1. "Changelog" translation is missing.
![image](https://github.com/ploi/roadmap/assets/23020662/c94c270b-5191-49e4-8110-d3f951bd7fc5)

2. "date" in "Comments" needs to be translated; you can use the same translation as in "Elementos."
![image](https://github.com/ploi/roadmap/assets/23020662/fafb91ad-5022-4d8c-87f8-d1ea4a5164e8)

3. "View Public" translation is missing.
![image](https://github.com/ploi/roadmap/assets/23020662/7bdad1c6-8f80-4c99-b64f-8228f6c11ed4)

4. There is an error because the text does exist and is translated, but it is not displayed correctly.
![image](https://github.com/ploi/roadmap/assets/23020662/186c70bb-8d23-41b5-a440-3a943c2790c2)

5. The following text is missing translation: "Choose a font family from Bunny Fonts (e.g., 'Roboto')"
![image](https://github.com/ploi/roadmap/assets/23020662/cda5534a-c5c1-41fa-91e4-f239949d8778)

6. Email validation needs translation.
![image](https://github.com/ploi/roadmap/assets/23020662/0f7d6af7-0534-4595-bba6-c1f2000b09f9)

7. Verification message.
![image](https://github.com/ploi/roadmap/assets/23020662/7f2d08bc-4d61-4bf5-baea-9b0d1d10ca7a)

8. Texts of the email.
![image](https://github.com/ploi/roadmap/assets/23020662/6cc4e438-6c5d-436a-90a9-184c6861c1f4)

9. Some texts are missing in this email.
![image](https://github.com/ploi/roadmap/assets/23020662/8722fce3-b07f-4b84-9129-bdb47e6c73b9)


10. This text is missing when creating an element.
![image](https://github.com/ploi/roadmap/assets/23020662/7011678a-c604-4a91-8d38-2828f4710526)

**Comment by Autive** [comment]
@adaniieel if im correct all the mentioned translations are now fixed.

**Comment by Cannonb4ll** [comment]
Excellent!
