### ISSUE TITLE
I suggest documenting the official app update process.

### ISSUE THREAD

**Issue by adaniieel** [ploi/roadmap#262]
For example, I am using the following, but I don't know if it is quite right.

1.Updating is currently done via Git version control. To update roadmap you can run the three following commands in the root directory of the application:
```
git pull origin main
composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
php artisan migrate
```
2. In addition, Clearing the system caches is also recommended:
```
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```

**Comment by Cannonb4ll** [comment]
It is all described here: https://github.com/ploi/roadmap?tab=readme-ov-file#deployment
