### ISSUE TITLE
Users management

### ISSUE THREAD

**Issue by ahuret** [ploi/roadmap#279]
Hello :wave: 

First, thank you for having open sourced this nice software !

I'm installing "roadmap" as part of my platform and I wonder how I will manage users.
All applications I use usually sync users with LDAP, I don't have SSO/Oauth2 implemented (yet).
I don't think this is possible by now with "roadmap" to have it synced with LDAP, another solution would be to have an API route that would allow to create users, but as I see it doesn't exists, am I right ?

Is one of those two ways exists by now or otherwise could/should be added ?

Thank you by advance !

**Comment by Cannonb4ll** [comment]
That's correct, for now there's no LDAP support. We do have SSO support as you might of noticed.

Feel free to submit a PR that covers this!
